#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")"   # deploy/ — frontend/config.js is at ../js/config.js
WAIT=false; [ "${1:-}" = "--wait" ] && WAIT=true
check_once() {
  echo "--- Containers ---"; sudo docker compose ps || return 1
  echo; echo "--- nginx health ---"; curl -fsS http://localhost/healthz || return 1
  echo; echo "--- Fineract direct ---"; curl -kfsS https://localhost:8443/fineract-provider/actuator/health || return 1
  echo; echo "--- Fineract via proxy ---"; curl -kfsS https://localhost/fineract/fineract-provider/actuator/health || return 1
  echo; echo "--- frontend index (catches the '/healthz OK but blank page' case) ---"
  curl -kfsS https://localhost/ | grep -qi "<title>FinCraft" || { echo "FAIL: index.html missing or not FinCraft's build"; return 1; }
  curl -kfsS https://localhost/js/app.js -o /dev/null || { echo "FAIL: js/app.js not served (frontend clone incomplete?)"; return 1; }
  echo "Frontend index + app.js present."
  echo; echo "--- config (deployed) ---"; grep -n "TENANT_MAP\|detectTenant\|LOCALE\|apiBase\|serverUrl" ../js/config.js || true
  grep -q "auto-generated by regen-frontend-config.sh" ../js/config.js || echo "WARNING: config.js does not look like the auto-generated version (still points at the repo's demo defaults?)"
  return 0
}
if [ "$WAIT" = true ]; then
  for i in $(seq 1 60); do check_once && { echo; echo "All health checks passed."; exit 0; }; echo "Waiting ${i}/60"; sleep 30; done
  echo "Timed out."; sudo docker logs fineract-server --tail 120 || true; exit 1
else check_once; fi
