#!/usr/bin/env bash
# Regenerates <frontend-root>/js/config.js from TENANT_DOMAINS in .env.
# Single source of truth used by setup-vm.sh, fincraft-autoupdate.sh, and
# redeploy.sh — previously this logic was duplicated in three places, which
# is exactly how it drifted out of sync with itself.
#
# Frontend lives at the repo root (one level above this deploy/ folder).
# Usage: ./regen-frontend-config.sh [FRONTEND_DIR] [--reload]
set -euo pipefail
cd "$(dirname "$0")"
set -a; . ./.env 2>/dev/null || true; set +a

FRONTEND_DIR="${1:-..}"
RELOAD=false; [ "${2:-}" = "--reload" ] && RELOAD=true

DEFAULT_TENANT_IDENTIFIER="${DEFAULT_TENANT_IDENTIFIER:-fincraft}"
PRIMARY_DOMAIN="$(echo "${DOMAINS:-}" | awk '{print $1}')"
TENANT_DOMAINS="${TENANT_DOMAINS:-${PRIMARY_DOMAIN:+${PRIMARY_DOMAIN}:${DEFAULT_TENANT_IDENTIFIER}}}"

mkdir -p "$FRONTEND_DIR/js"
{
cat <<CFG_HEAD
/* FinCraft config - auto-generated by regen-frontend-config.sh. DO NOT EDIT
   BY HAND — it will be overwritten on the next deploy/redeploy/auto-update.
   Same-origin via nginx proxy. MULTI-TENANT: the tenant is chosen from the
   browser hostname via this explicit map, generated from TENANT_DOMAINS in
   .env. add-tenant.sh extends TENANT_DOMAINS for every tenant added
   afterward. An unmapped hostname falls back to the '${DEFAULT_TENANT_IDENTIFIER}'
   tenant (this deploy's DEFAULT_TENANT_IDENTIFIER / Fineract's
   FINERACT_DEFAULT_TENANTDB_IDENTIFIER — see .env and docker-compose.yml). */

const TENANT_MAP = {
CFG_HEAD
for pair in $TENANT_DOMAINS; do
  d="${pair%%:*}"; t="${pair#*:}"
  [ -n "$d" ] && [ -n "$t" ] && printf "  '%s': '%s',\n" "$d" "$t"
done
cat <<CFG_TAIL
};

function detectTenant() {
  const host = (typeof location !== 'undefined' && location.hostname) ? location.hostname : '';
  return TENANT_MAP[host] || '${DEFAULT_TENANT_IDENTIFIER}';
}

export const LOCALE      = 'en';
export const DATE_FORMAT = 'yyyy-MM-dd';
export function today() { return new Date().toISOString().split('T')[0]; }

export const FINERACT_DEMO = {
  // Same-origin, shown to the user (not left blank) so the login screen's
  // Server URL field is auto-filled just like Tenant ID is.
  serverUrl:  (typeof location !== 'undefined' && location.origin) ? location.origin : '',
  tenantId:   detectTenant(),
  apiBase:    '/fineract/fineract-provider/api/v1',
  requestTimeoutMs:     45000,
  autoConnectTimeoutMs: 15000
};

export function getRuntimeConfig() {
  return {
    tenantId:             FINERACT_DEMO.tenantId,
    apiBase:              FINERACT_DEMO.apiBase,
    requestTimeoutMs:     FINERACT_DEMO.requestTimeoutMs,
    autoConnectTimeoutMs: FINERACT_DEMO.autoConnectTimeoutMs
  };
}
CFG_TAIL
} > "$FRONTEND_DIR/js/config.js"

echo "Wrote $FRONTEND_DIR/js/config.js for tenants: ${TENANT_DOMAINS:-<none>}"

if [ "$RELOAD" = true ]; then
  docker exec fincraft-ui nginx -s reload 2>/dev/null || sudo -n docker exec fincraft-ui nginx -s reload 2>/dev/null || true
fi
